from streamlit_pandas_profiling import st_profile_report
from ydata_profiling import ProfileReport
from streamlit_pages.utils import get_table_df
import streamlit as st
import pandas as pd


def database_analysis_page():

    database_selected = st.radio("Select database option to analyze", ["Parishioners Database", "Payments Databas"])
    
    if database_selected == "Parishioners Database":
        table_name = "parishioners"
    else:
        table_name = "payments"

    profile = ProfileReport((get_table_df(table_name)),
        title= database_selected,
        variables={
            "description": f'This profiling report was generated by Roylan D. Pais for the analysis of HTC {database_selected}',
        }) 
    
    st_profile_report(profile)
